// export const ACTION_TYPE = {
//   INCREMENT: "INCREMENT",
//   DECREMENT: "DECREMENT",
//   RESET: "RESET",
// };

export const ACTION_TYPE = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
};
